### ISSUE TITLE
Cuda Error

### ISSUE THREAD

**Issue by Hydrahfw** [john-mnz/ComfyUI-Inspyrenet-Rembg#36]
When trying to run the node as per the workflow, I get this error:

Failed to auto-detect CUDA root directory. Please specify `CUDA_PATH` environment variable if you are using CUDA versions not yet supported by CuPy.

Sorry if this is a simple fix, im not very experienced with comfyui.

**Comment by hwprinz** [comment]
hey friend, i'm having the exact same error, but havent found a fix yet. also i'm having a 2nd 'duplicated' installation, where the error does not happen.
so, the difference is
installation with error, i have:
transparent-background 1.3.4
flet 0.28.3

installation without error, i have:
transparent-background 1.3.3
flet 0.25.2

and i mean, i had to fix the one without error a while back by downgrading these two packages.

BUT:
i have a third installation, where i still have both these packages are still on the newer versions, and it runs perfectly fine...

so, right now, i'm a little stuck, trying to find other reasons why this is happening 

nonetheless, it would be interesting, what versions you have...
Thanks

**Comment by babaBOOOO** [comment]
> When trying to run the node as per the workflow, I get this error:
> 
> Failed to auto-detect CUDA root directory. Please specify `CUDA_PATH` environment variable if you are using CUDA versions not yet supported by CuPy.
> 
> Sorry if this is a simple fix, im not very experienced with comfyui.

hey i had the same issue. you need to install the CUDA toolkit from NVIDIA then restart your pc. this fixed it for me. here's the link or you can search 'nvidia cuda toolkit' on google

https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local

**Comment by hwprinz** [comment]
No, You don't  !!!!!
there is never CUDA toolkit needed for this custom node
